### PR TITLE
Update __init__.py with changes to setup

### PR DESCRIPTION
**Pull request by Fripe070**
See https://github.com/Breadcord/Breadcord/pull/264

### CODE REVIEW

**Comment by m31-galaxy** [comment]
Do you think we should remove the redundant `__init__` subclass while we're at it?

**Comment by Fripe070** [comment]
We could, but I added it so it's a bit easier to add more to it. We could just get rid of it if you prefer though

**Comment by m31-galaxy** [comment]
I think a more minimal template in that regard would be preferred, as not every module needs it.

**Comment by Fripe070** [comment]
We will have to agree to disagree there, I’m merging this PR and you can go ahead and implement your suggested change if you so wish

**Pull request merged**
